[client]
node_addresses = ["http://127.0.0.1:50051"]
encoder_params = ["-vf", "scale=1920:-1", "-c:v", "libsvtav1", "-preset", "4", "-crf", "50","-pix_fmt" ,"yuv420p10le"]

[node]
address = "0.0.0.0:50051"
node_address = "0.0.0.0:50051"
temp_dir = "./server_50051"

[processing]
segment_duration = 60.0
temp_dir = "./temp"