style_edition = "2021"
newline_style = "Unix"
use_small_heuristics = "Default"

max_width = 100
hard_tabs = false
tab_spaces = 4
wrap_comments = true
comment_width = 80
chain_width = 80
array_width = 80
attr_fn_like_width = 70

imports_indent = "Block"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
empty_item_single_line = false

binop_separator = "Front"
overflow_delimited_expr = true
reorder_impl_items = false
struct_field_align_threshold = 30
struct_lit_single_line = false
fn_params_layout = "Tall"
match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
type_punctuation_density = "Wide"

indent_style = "Block"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false

force_explicit_abi = true
disable_all_formatting = false